### PR TITLE
Forpullrequests

### PR DESCRIPTION
**Pull request by piotrskowronski**
Thin optics for flat V

### CODE REVIEW

**Comment by rdemaria** [comment]
Many thanks! Can you use the directory squeeze_flathv instead, e.g.:

```
git mv  squeeze/flatVH squeeze_flathv
```

Thanks again,
Riccardo

**Comment by piotrskowronski** [comment]
Done. 
Added also the branch with direct 125/400 -> 075/300

**Comment by piotrskowronski** [comment]
Pages with plots for the produced optices

Via 100/400 thick
http://skowron.web.cern.ch/skowron/hllhc13/flat/h/pass16end/doc.html

Via 100/400 thin
http://skowron.web.cern.ch/skowron/hllhc13/flat/h/pass16thin/doc.html

From 125/400 directly to 075/300 thick
http://skowron.web.cern.ch/skowron/hllhc13/flat/h/pass18end/doc.html

From 125/400 directly to 075/300 thin
http://skowron.web.cern.ch/skowron/hllhc13/flat/h/pass18thin/doc.html

**Comment by rdemaria** [comment]
I am merging. Do you plan to keep the web pages? If you want I can put them  in the optics website..

**Comment by piotrskowronski** [comment]
I will keep them at least for some time, but you can also copy them.

Piotr

**Pull request merged**
